name: calaurd
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  auto_size_text: 3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - packages/calaurd/assets/images/409_106.png
    - packages/calaurd/assets/images/409_162.png
    - packages/calaurd/assets/images/409_165.png
    - packages/calaurd/assets/images/409_168.png
    - packages/calaurd/assets/images/409_173.png
    - packages/calaurd/assets/images/409_174.png
    - packages/calaurd/assets/images/409_175.png
    - packages/calaurd/assets/images/409_176.png
    - packages/calaurd/assets/images/409_184.png
    - packages/calaurd/assets/images/409_188.png
    - packages/calaurd/assets/images/409_190.png
    - packages/calaurd/assets/images/409_349.png
    - packages/calaurd/assets/images/409_357.png
    - packages/calaurd/assets/images/409_361.png
    - packages/calaurd/assets/images/I516_24;409_352.png
    - packages/calaurd/assets/images/I516_24;409_353.png
    - packages/calaurd/assets/images/409_373.png
    - packages/calaurd/assets/images/I510_12;409_352.png
    - packages/calaurd/assets/images/I510_12;409_353.png
    - packages/calaurd/assets/images/409_385.png
    - packages/calaurd/assets/images/I510_15;409_352.png
    - packages/calaurd/assets/images/I510_15;409_353.png
    - packages/calaurd/assets/images/409_395.png
    - packages/calaurd/assets/images/409_400.png
    - packages/calaurd/assets/images/409_408.png
    - packages/calaurd/assets/images/409_93.png
    - packages/calaurd/assets/images/409_97.png
